### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by bashcode** [yassineaddi/BackdoorMan#2]
Hello,

Maybe you can use my own script for detect phpshells and malicious files, we using own database with no false positives.

https://github.com/bashcode/Pyscan

Regards!

**Comment by yassineaddi** [comment]
Hello @bashcode,

I gave it a try, with a list of destinations (especially created for testing purposes) but it failed in most of them. I will appreciate working on the existing detect algorithme in the BackdoorMan and then do a pull request for any part you can improve (take a look at the TODO list).

The BackdoorMan is sometimes giving false positives because it needs improvements especially in large projects installations like WordPress. I'm working on this beside other features that will be available in next release. Until then, your contributions are welcome!

Thank you for using it!
Yassine.
