### ISSUE TITLE
Missing Scripts that harm your web server too.

### ISSUE THREAD

**Issue by 0thm4n3** [yassineaddi/BackdoorMan#3]
Hello there Yassine,

as an IT Security Consultant I always find advanced scripts used to hack some servers or websites, so when you name all those shells in BackdoorMan/databases/shells.txt this list looks so poor of names, especially that hackers are not using most of these shells anymore, HOW ?

Hackers these days are uploading PHP mailers to do send phishing mails and this types of scripts has functions to Remotely Execute commands or Execute Codes without a need of C99 or R57 shell scripts, Hackers also upload self made backdoor ( I am not talking about script kiddies at this point ) so most of these scripts are not detectable on most of them are encoded with base64 for PHP and other backdoors made with other languages such as Ruby, Python and perl ...etc.

So I'd suggest you to add more and more scripts names and functions which are being used to do suspected actions such as Remote code/command execution, backconnects ...etc, and finally this API ( http://www.unphp.net/api/ ) well help you so much to decode most of the encoded PHP scripts and analyse them automatically by BackdoorMan.

Finally, I really loved your project it has no problems, no bugs and no security issues that's why I loved it so much, and that's a result of a code made by love.

Best regards,

Othmane Tamagart | IT Security Consultant at www.secomunity.com

**Comment by yassineaddi** [comment]
Hi **Othmane**,

I suppose you didn't read the source or even the description, I invite you to do that as you misunderstood or didn't pay attention to what the tool is actually doing.
The time you spent writing this novel, you could spent it on reading the description at least.

First of all, I'm not relying on the database that contains the shells' names to detect back-doors, it's a process that the tool is doing to provide the user with quick information and suspicious files, there are a lot of beginners out there - or "kiddies" if you wish to call them like so - that use the shell as it is without renaming it. So, instead of analyzing the files directly, I see that's better to let the user know if it's a possible threat. I like to call it snacks/starters. Once again I invite you to read the source code.

2nd. It looks like you didn't even try it! anyway, all what you've said about self-made back-doors and base64 encoding...etc is already handled by the tool. So, without further talk, give it a try to make sure.
Also, it's clear that the tool detects **PHP** shells and suspicious scripts...etc ONLY, I don't have the time nor experience to make it handle the cases of other programming languages.

3rd. Seriously? just read the description, it's obviously mentioned that the tool is using a complex algorithm and use APIs (external services) beside it's functionalities! the funny thing about it is that... yeah, the tool is using the unphp API too.

I appreciate that you like it, but come on! as a part of your job, you need to give things a shot before judging.

Greetings.
